// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: bifrostpb/bifrost.proto

package bifrostpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token       string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	SvrName     string `protobuf:"bytes,2,opt,name=SvrName,proto3" json:"SvrName,omitempty"`
	RequestType string `protobuf:"bytes,3,opt,name=RequestType,proto3" json:"RequestType,omitempty"`
	Param       string `protobuf:"bytes,4,opt,name=Param,proto3" json:"Param,omitempty"`
	Data        []byte `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bifrostpb_bifrost_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_bifrostpb_bifrost_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_bifrostpb_bifrost_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Request) GetSvrName() string {
	if x != nil {
		return x.SvrName
	}
	return ""
}

func (x *Request) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *Request) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret []byte `protobuf:"bytes,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bifrostpb_bifrost_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_bifrostpb_bifrost_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_bifrostpb_bifrost_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetRet() []byte {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_bifrostpb_bifrost_proto protoreflect.FileDescriptor

var file_bifrostpb_bifrost_proto_rawDesc = []byte{
	0x0a, 0x17, 0x62, 0x69, 0x66, 0x72, 0x6f, 0x73, 0x74, 0x70, 0x62, 0x2f, 0x62, 0x69, 0x66, 0x72,
	0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x62, 0x69, 0x66, 0x72, 0x6f,
	0x73, 0x74, 0x70, 0x62, 0x22, 0x85, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x76, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x76, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2e, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x72, 0x72, 0x32, 0xc1, 0x01, 0x0a,
	0x0e, 0x42, 0x69, 0x66, 0x72, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x36, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x2e, 0x62, 0x69, 0x66,
	0x72, 0x6f, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x62, 0x69, 0x66, 0x72, 0x6f, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3b, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x2e, 0x62, 0x69, 0x66, 0x72, 0x6f, 0x73,
	0x74, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x62, 0x69,
	0x66, 0x72, 0x6f, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x12, 0x3a, 0x0a, 0x09, 0x57, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x12, 0x2e, 0x62, 0x69, 0x66, 0x72, 0x6f, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x62, 0x69, 0x66, 0x72, 0x6f, 0x73, 0x74, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x1d, 0x5a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x62, 0x69, 0x66, 0x72, 0x6f, 0x73, 0x74, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bifrostpb_bifrost_proto_rawDescOnce sync.Once
	file_bifrostpb_bifrost_proto_rawDescData = file_bifrostpb_bifrost_proto_rawDesc
)

func file_bifrostpb_bifrost_proto_rawDescGZIP() []byte {
	file_bifrostpb_bifrost_proto_rawDescOnce.Do(func() {
		file_bifrostpb_bifrost_proto_rawDescData = protoimpl.X.CompressGZIP(file_bifrostpb_bifrost_proto_rawDescData)
	})
	return file_bifrostpb_bifrost_proto_rawDescData
}

var file_bifrostpb_bifrost_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bifrostpb_bifrost_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: bifrostpb.Request
	(*Response)(nil), // 1: bifrostpb.Response
}
var file_bifrostpb_bifrost_proto_depIdxs = []int32{
	0, // 0: bifrostpb.BifrostService.GetInfo:input_type -> bifrostpb.Request
	0, // 1: bifrostpb.BifrostService.UpdateConfig:input_type -> bifrostpb.Request
	0, // 2: bifrostpb.BifrostService.WatchInfo:input_type -> bifrostpb.Request
	1, // 3: bifrostpb.BifrostService.GetInfo:output_type -> bifrostpb.Response
	1, // 4: bifrostpb.BifrostService.UpdateConfig:output_type -> bifrostpb.Response
	1, // 5: bifrostpb.BifrostService.WatchInfo:output_type -> bifrostpb.Response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bifrostpb_bifrost_proto_init() }
func file_bifrostpb_bifrost_proto_init() {
	if File_bifrostpb_bifrost_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bifrostpb_bifrost_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bifrostpb_bifrost_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bifrostpb_bifrost_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bifrostpb_bifrost_proto_goTypes,
		DependencyIndexes: file_bifrostpb_bifrost_proto_depIdxs,
		MessageInfos:      file_bifrostpb_bifrost_proto_msgTypes,
	}.Build()
	File_bifrostpb_bifrost_proto = out.File
	file_bifrostpb_bifrost_proto_rawDesc = nil
	file_bifrostpb_bifrost_proto_goTypes = nil
	file_bifrostpb_bifrost_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BifrostServiceClient is the client API for BifrostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BifrostServiceClient interface {
	GetInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (BifrostService_GetInfoClient, error)
	UpdateConfig(ctx context.Context, opts ...grpc.CallOption) (BifrostService_UpdateConfigClient, error)
	WatchInfo(ctx context.Context, opts ...grpc.CallOption) (BifrostService_WatchInfoClient, error)
}

type bifrostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBifrostServiceClient(cc grpc.ClientConnInterface) BifrostServiceClient {
	return &bifrostServiceClient{cc}
}

func (c *bifrostServiceClient) GetInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (BifrostService_GetInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BifrostService_serviceDesc.Streams[0], "/bifrostpb.BifrostService/GetInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &bifrostServiceGetInfoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BifrostService_GetInfoClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type bifrostServiceGetInfoClient struct {
	grpc.ClientStream
}

func (x *bifrostServiceGetInfoClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bifrostServiceClient) UpdateConfig(ctx context.Context, opts ...grpc.CallOption) (BifrostService_UpdateConfigClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BifrostService_serviceDesc.Streams[1], "/bifrostpb.BifrostService/UpdateConfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &bifrostServiceUpdateConfigClient{stream}
	return x, nil
}

type BifrostService_UpdateConfigClient interface {
	Send(*Request) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type bifrostServiceUpdateConfigClient struct {
	grpc.ClientStream
}

func (x *bifrostServiceUpdateConfigClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bifrostServiceUpdateConfigClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bifrostServiceClient) WatchInfo(ctx context.Context, opts ...grpc.CallOption) (BifrostService_WatchInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BifrostService_serviceDesc.Streams[2], "/bifrostpb.BifrostService/WatchInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &bifrostServiceWatchInfoClient{stream}
	return x, nil
}

type BifrostService_WatchInfoClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type bifrostServiceWatchInfoClient struct {
	grpc.ClientStream
}

func (x *bifrostServiceWatchInfoClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bifrostServiceWatchInfoClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BifrostServiceServer is the server API for BifrostService service.
type BifrostServiceServer interface {
	GetInfo(*Request, BifrostService_GetInfoServer) error
	UpdateConfig(BifrostService_UpdateConfigServer) error
	WatchInfo(BifrostService_WatchInfoServer) error
}

// UnimplementedBifrostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBifrostServiceServer struct {
}

func (*UnimplementedBifrostServiceServer) GetInfo(*Request, BifrostService_GetInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (*UnimplementedBifrostServiceServer) UpdateConfig(BifrostService_UpdateConfigServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (*UnimplementedBifrostServiceServer) WatchInfo(BifrostService_WatchInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchInfo not implemented")
}

func RegisterBifrostServiceServer(s *grpc.Server, srv BifrostServiceServer) {
	s.RegisterService(&_BifrostService_serviceDesc, srv)
}

func _BifrostService_GetInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BifrostServiceServer).GetInfo(m, &bifrostServiceGetInfoServer{stream})
}

type BifrostService_GetInfoServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type bifrostServiceGetInfoServer struct {
	grpc.ServerStream
}

func (x *bifrostServiceGetInfoServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _BifrostService_UpdateConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BifrostServiceServer).UpdateConfig(&bifrostServiceUpdateConfigServer{stream})
}

type BifrostService_UpdateConfigServer interface {
	SendAndClose(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type bifrostServiceUpdateConfigServer struct {
	grpc.ServerStream
}

func (x *bifrostServiceUpdateConfigServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bifrostServiceUpdateConfigServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BifrostService_WatchInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BifrostServiceServer).WatchInfo(&bifrostServiceWatchInfoServer{stream})
}

type BifrostService_WatchInfoServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type bifrostServiceWatchInfoServer struct {
	grpc.ServerStream
}

func (x *bifrostServiceWatchInfoServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bifrostServiceWatchInfoServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BifrostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bifrostpb.BifrostService",
	HandlerType: (*BifrostServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetInfo",
			Handler:       _BifrostService_GetInfo_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateConfig",
			Handler:       _BifrostService_UpdateConfig_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchInfo",
			Handler:       _BifrostService_WatchInfo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bifrostpb/bifrost.proto",
}
