name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: bifrost-auth Build Test
      run: go build -v -race
      working-directory: ./cmd/bifrost-auth
      
    - name: bifrost Build Test
      run: go build -v -race
      working-directory: ./cmd/bifrost
      
    - name: ng_conf_format Build Test
      run: go build -v -race
      working-directory: ./cmd/ng_conf_format

    # - name: Test
    #   run: go test -v ./...
